version: '3.7'

services:

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8060:80

  dev:
    container_name: dev
    command: ["pnpm", "start"]
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-deps
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
